name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  front:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    -
      name: Install, Tests & build
      run: |
        npm install
        npm test
        npm run build
    -
      name: Docker build image front
      run: docker build -t yolanmq/front-devops-project:latest -f Dockerfile.front .
    -
      name: Docker push image front
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login $DOCKER_REGISTRY --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push yolanmq/front-devops-project:latest

  back:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: Docker build image front
        run: docker build -t yolanmq/back-devops-project:latest -f Dockerfile.back .
      -
        name: Docker push image front
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login $DOCKER_REGISTRY --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push yolanmq/back-devops-project:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [front, back]

    steps:
      - 
        name: SSH key gen
        run: ssh-keygen -f ~/.ssh/terraform -t rsa -m PEM -q -N ""
      - 
        name: Install terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          apt install terraform
      -
        name: Install Scaleway cli
        run: |
          curl -o /usr/local/bin/scw -L "https://github.com/scaleway/scaleway-cli/releases/download/v2.2.3/scw-2.2.3-linux-x86_64"
          chmod +x /usr/local/bin/scw
          scw init
