name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  front:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    -
      name: Install, Tests & build
      run: |
        npm install
        npm test
        npm run build
    -
      name: Docker build image front
      run: docker build -t yolanmq/front-devops-project:latest -f Dockerfile.front .
    -
      name: Docker push image front
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login $DOCKER_REGISTRY --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push yolanmq/front-devops-project:latest

  back:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: Docker build image back
        run: docker build -t yolanmq/back-devops-project:latest -f Dockerfile.back .
      -
        name: Docker push image back
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login $DOCKER_REGISTRY --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push yolanmq/back-devops-project:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [front, back]

    steps:
      - 
        name: SSH key gen
        run: |
          echo "${{ secrets.SSH_SECRET }}" > ssh_key

      - 
        name: Scaleway scw CLI
        uses: jawher/action-scw@v2.0.0-2
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_ORGANIZATION_ID: ${{ secrets.SCALEWAY_ORGANIZATION }}
          SCW_ZONE: fr-par-2
        with:
           args: account ssh-key add name=terraform public-key=./ssh/ssh-key.pub organization-id=${{ secrets.SCALEWAY_ORGANIZATION }}
      -
        name: Terraform setup
        uses: hashicorp/setup-terraform@v1
      -
        name: Terraform init & apply
        run: |
          terraform init
          terraform apply -auto-approve
